apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregator-config
data:
  aggregator-config.yml: |
    type: aggregator

    gitUserToken: 1qaz_WSX
    aggregatorModelRepo:
      gitHttpURL: http://aggregator@harmonia-gitea:3000/gitea/global-model.git
    edgeModelRepos:
      - gitHttpURL: http://aggregator@harmonia-gitea:3000/gitea/local-model1.git
      - gitHttpURL: http://aggregator@harmonia-gitea:3000/gitea/local-model2.git
    trainPlanRepo:
      gitHttpURL: http://aggregator@harmonia-gitea:3000/gitea/train-plan.git

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: edge1-config
data:
  edge-config.yml: |
    type: edge

    gitUserToken: 1qaz_WSX
    aggregatorModelRepo:
      gitHttpURL: http://edge1@harmonia-gitea:3000/gitea/global-model.git
    edgeModelRepo:
      gitHttpURL: http://edge1@harmonia-gitea:3000/gitea/local-model1.git
    trainPlanRepo:
      gitHttpURL: http://edge1@harmonia-gitea:3000/gitea/train-plan.git

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: edge2-config
data:
  edge-config.yml: |
    type: edge

    gitUserToken: 1qaz_WSX
    aggregatorModelRepo:
      gitHttpURL: http://edge2@harmonia-gitea:3000/gitea/global-model.git
    edgeModelRepo:
      gitHttpURL: http://edge2@harmonia-gitea:3000/gitea/local-model2.git
    trainPlanRepo:
      gitHttpURL: http://edge2@harmonia-gitea:3000/gitea/train-plan.git
