# Gitea
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-deployment
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image: gitea/gitea
          ports:
            - containerPort: 3000
              name: gitea
            - containerPort: 22
              name: git-ssh
          envFrom:
            - configMapRef:
                name: gitea-config

---
kind: Service
apiVersion: v1
metadata:
  name: harmonia-gitea
spec:
  selector:
    app: gitea
  ports:
  - name: gitea-http
    port: 3000
    targetPort: 3000
  - name: gitea-ssh
    port: 2222
    targetPort: 22
  type: NodePort
